version: '3.5'

services:
  front:
    container_name: famgFront
    build: ./front/
    image: front:v1
    command: yarn serve
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "8081:8080"
    networks:
      - goapinet
    environment:
      - VIRTUAL_HOST=front.suchil.dev
  back:
    container_name: famgBack
    build: ./back/
    image: back:v1
    volumes:
      - ./back/:/app
    ports:
      - "8080:80"
    networks:
      - goapinet
    environment:
      - VIRTUAL_HOST=back.suchil.dev

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres_goapi:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - goapinet
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-suchilin@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-secret}
    volumes:
      - pgadmin_goapi:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - goapinet
    restart: unless-stopped
  dnsmasq:
    container_name: dnsmasq
    image: andyshinn/dnsmasq:latest
    command: --log-queries --log-facility=- --address=/suchil.dev/127.0.0.1
    ports:
      - 53:53
      - 53:53/udp
    cap_add:
      - NET_ADMIN
    networks:
      - goapinet
  nginx-proxy:
    container_name: ngix-proxy
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - goapinet

networks:
  goapinet:
    driver: bridge

volumes:
    postgres_goapi:
    pgadmin_goapi:
